- name: docker build and push
  hosts: local
  become: no

  tasks:

    - name: Build Docker Image
      command: docker build -t jpetstore .
      args:
        chdir: /var/lib/jenkins/workspace/petstore/jpetstore-6

    - name: Tag image
      command: docker tag jpetstore:latest samiracavalcanti/jpetstore:latest

    - name: Login Docker Hub
      shell: echo "$DOCKERHUB_PASSWORD" | docker login -u samiracavalcanti --password-stdin
      environment:
        DOCKERHUB_PASSWORD: "{{ lookup('env', 'DOCKERHUB_PASSWORD_PSW') }}"

    - name: Push image
      command: docker push samiracavalcanti/jpetstore:latest

    - name: Remove old container
      command: docker rm -f pet1
      ignore_errors: yes

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 samiracavalcanti/jpetstore:latest