- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: no  # Jenkins user already in docker group

  tasks:
    - name: Build Docker Image
      command: docker build -t jpetstore .
      args:
        chdir: /var/lib/jenkins/workspace/petstore/jpetstore-6

    - name: tag image
      command: docker tag jpetstore:latest samiracavalcanti/jpetstore:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: samiracavalcanti
        password: "{{ lookup('env', 'DOCKERHUB_PASSWORD') }}"

    - name: Push image
      command: docker push samiracavalcanti/jpetstore:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 samiracavalcanti/jpetstore:latest
